### ISSUE TITLE
Is the list of projects updated for the 2019 program?

### ISSUE THREAD

**Issue by InTheLapOfTheGods** [openmainframeproject/tsc#19]
I saw VMlink automounter listed in proposed.md and I saw that one of 2018 interns is already working on this project https://github.com/trothr/vmlink/commits?author=rusrushal13

Is this project still under development for the 2019 internship program or is the list not updated? I would like to know which projects are the one that will be a part of the 2019 internship program

I had another question do the selection depends on previous contributions to the project for which candidate is applying because for some projects it was not clear where to find the codebase to contribute to, I would like to start to contributing now to get familar with different projects

**Comment by InTheLapOfTheGods** [comment]
cc @jmertic

**Comment by jmertic** [comment]
Good question! I've been working with the community to review the project lists and come up with more ideas. Stay tuned!

**Comment by InTheLapOfTheGods** [comment]
thanks for the reply
